// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALSxPWmYYb9BZ5vv8g4qT5sLlKcBzWP1c',
    appId: '1:633396942184:web:18f2cc8a1eb21ef98532dd',
    messagingSenderId: '633396942184',
    projectId: 'virtual-tourism-trenggalek',
    authDomain: 'virtual-tourism-trenggalek.firebaseapp.com',
    storageBucket: 'virtual-tourism-trenggalek.firebasestorage.app',
    measurementId: 'G-9QL704ZETF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAY0Bk9phP8S0C_jQMKjXkR00bH74X41M',
    appId: '1:633396942184:android:1759e71ea22302a08532dd',
    messagingSenderId: '633396942184',
    projectId: 'virtual-tourism-trenggalek',
    storageBucket: 'virtual-tourism-trenggalek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkDj-Bosk3UyB_RirrVSrn5RKFha5F51E',
    appId: '1:633396942184:ios:120aca3b2462a42a8532dd',
    messagingSenderId: '633396942184',
    projectId: 'virtual-tourism-trenggalek',
    storageBucket: 'virtual-tourism-trenggalek.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiWisata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkDj-Bosk3UyB_RirrVSrn5RKFha5F51E',
    appId: '1:633396942184:ios:120aca3b2462a42a8532dd',
    messagingSenderId: '633396942184',
    projectId: 'virtual-tourism-trenggalek',
    storageBucket: 'virtual-tourism-trenggalek.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiWisata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALSxPWmYYb9BZ5vv8g4qT5sLlKcBzWP1c',
    appId: '1:633396942184:web:722a5538a34376848532dd',
    messagingSenderId: '633396942184',
    projectId: 'virtual-tourism-trenggalek',
    authDomain: 'virtual-tourism-trenggalek.firebaseapp.com',
    storageBucket: 'virtual-tourism-trenggalek.firebasestorage.app',
    measurementId: 'G-CEMHKSSFCE',
  );
}